sudo: required

language: node_js

node_js:
  - "9"

services:
- docker

cache:
  directories:
  - node_modules

before_install:
  - docker build -f ./misc/eth/Dockerfile -t eth .
  - docker run --rm -dit -p 30304:30304 -p 8000:8000 --name ethdevnet eth:latest
  - sleep 180

install:
  - npm install -g truffle
  - npm install
  - npm install --save-dev solidity-coverage

script:
  - cd eth
  - truffle test
  - ../node_modules/.bin/solidity-coverage 

after_script:
  - docker kill ethdevnet
#- npm run coverage && cat coverage/lcov.info | coveralls