sudo: required

language: node_js

node_js:
  - "9"

cache:
  directories:
  - node_modules

before_install:
  - sudo add-apt-repository ppa:ethereum/ethereum -y
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common wget
  - wget https://dl.google.com/go/go1.10.linux-amd64.tar.gz
  - sudo tar -xvf go1.10.linux-amd64.tar.gz
  - sudo mv go /usr/local
  - mkdir $HOME/go
  - export GOROOT=/usr/local/go
  - export GOPATH=$HOME/go
  - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
  - sudo apt-get install -y ethereum

install:
  - npm install -g truffle
  - npm install
  - npm install --save-dev solidity-coverage
  - npm install -g ganache-cli
  - npm install truffle-hdwallet-provider
  - npm install truffle-assertions

script:
  - ganache-cli &
  - cd eth
  - truffle test --network development
#  - ../node_modules/.bin/solidity-coverage
  - cd ..
  - make all

#after_script:
#  - docker kill ethdevnet
#- npm run coverage && cat coverage/lcov.info | coveralls