sudo: required

language: node_js

node_js:
  - "9"

cache:
  directories:
  - node_modules

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get install -y golang ethereum

install:
  - npm install -g truffle
  - npm install
  - npm install --save-dev solidity-coverage
  - npm install -g ganache-cli
  - npm install truffle-hdwallet-provider
  - npm install truffle-assertions

script:
  - ganache-cli &
  - cd eth
  - truffle test --network development
#  - ../node_modules/.bin/solidity-coverage
  - cd ..
  - make all

#after_script:
#  - docker kill ethdevnet
#- npm run coverage && cat coverage/lcov.info | coveralls