version: '3'
services:
  fullnode:
    image: fullnode_snapshot
    build:
      dockerfile: ./misc/eth/Dockerfile
      context: ./
    networks:
      - ipfs-net
    tty: true
    ports:
      - "8001:8001"
    volumes:
      - ./eth:/ethcode
      - ./misc/eth:/ethnet

  alice:
    image: ipfs-share
    build:
      context: .
    networks:
      - ipfs-net
    ports:
      - "3333:3333"
      - "30311:30311"
      - "8501:8501"
    depends_on:
      - fullnode
    stdin_open: true
    tty: true
    volumes:
       - ./test/alice:/mounted

  bob:
      image: ipfs-share
      build:
        context: .
      networks:
        - ipfs-net
      ports:
        - "3334:3333"
        - "30312:30311"
        - "8502:8501"
      depends_on:
        - fullnode
      stdin_open: true
      tty: true
      volumes:
         - ./test/bob:/mounted

  charlie:
      image: ipfs-share
      build:
        context: .
      networks:
        - ipfs-net
      ports:
        - "3335:3333"
        - "30313:30311"
        - "8503:8501"
      depends_on:
        - fullnode
      stdin_open: true
      tty: true
      volumes:
         - ./test/charlie:/mounted
networks:
  ipfs-net: