version: '3'
services:
  server:
    image: server
    build:
      context: ./server
    networks:
      - ipfs-net

  alice:
    image: ipfs-share
    build:
      context: .
    networks:
      - ipfs-net
    ports:
      - "3333:3333"
    depends_on:
      - server

  bob:
      image: ipfs-share
      build:
        context: .
      networks:
        - ipfs-net
      ports:
        - "3334:3333"
      depends_on:
        - server

  charlie:
      image: ipfs-share
      build:
        context: .
      networks:
        - ipfs-net
      ports:
        - "3335:3333"
      depends_on:
        - server
networks:
  ipfs-net: